#define NEWLINE                         1
#define COLON                           2
#define ANDAND                          3
#define BARBAR                          4
#define IN                              5
#define IS                              6
#define EQEQ                            7
#define EXCLAIMEQ                       8
#define LT                              9
#define GT                             10
#define LTEQ                           11
#define GTEQ                           12
#define ADD                            13
#define MINUS                          14
#define STAR                           15
#define SLASH                          16
#define MOD                            17
#define EXCLAIM                        18
#define UNARYMINUS                     19
#define STARSTAR                       20
#define DOT                            21
#define SUBSCRIPT                      22
#define CALL                           23
#define GROUPING                       24
#define LAMBDA                         25
#define FATARROW                       26
#define ARROW                          27
#define QUESTIONMARK                   28
#define TYPE_GROUPING                  29
#define IDENT                          30
#define LPAREN                         31
#define RPAREN                         32
#define EQ                             33
#define NUMBER                         34
#define STRING                         35
#define LSQUARE                        36
#define RSQUARE                        37
#define LCURLY                         38
#define RCURLY                         39
#define COMMA                          40
#define YES                            41
#define NO                             42
#define TITLEIDENT                     43
